# Generated by Django 4.0.3 on 2022-03-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='to_mail',
        ),
        migrations.AddField(
            model_name='mail',
            name='to_mail',
            field=models.ManyToManyField(to='mail.tomail'),
        ),
    ]
