# Generated by Django 4.0.3 on 2022-03-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_remove_mail_to_mail_mail_to_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.DeleteModel(
            name='ToMail',
        ),
    ]
